<?php
/**
 * @file
 * Drupal module: Telegram manager
 *
 * Experimental development, guess what...
 *
 * By Jose Manuel Guerrero & Jose Reyero
 *
 * http://reyero.net
 * http://jmanuelguerrero.com
 */

use Drupal\telegram\DrupalTelegramStorage;
use Drupal\telegram\DrupalTelegramManager;

/**
 * Implements hook_menu().
 */
function telegram_manager_menu() {
   $items['admin/config/telegram/manager'] = array(
     'title' => 'Manager',
     'description' => 'Read Messages',
     'page callback' => 'telegram_manager_message_list_page',
     'access arguments' => array('administer site configuration'),
     'file' => 'telegram_manager.pages.inc',
   );
   $items['admin/config/telegram/manager/message'] = array(
     'title' => 'Messages',
     'description' => 'Read all messages',
     'type' => MENU_DEFAULT_LOCAL_TASK,
     'weight' => -10,
   );
   $items['admin/config/telegram/manager/message/%telegram_manager_message'] = array(
     'title' => 'Message',
     'description' => 'View message',
     'page callback' => 'telegram_manager_message_page',
     'page arguments' => array(5),
     'access arguments' => array('administer site configuration'),
     'file' => 'telegram_manager.pages.inc',
     'type' => MENU_CALLBACK,
   );
   $items['admin/config/telegram/manager/send'] = array(
     'title' => 'Send',
     'description' => 'Send message',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('telegram_manager_send_form'),
     'access arguments' => array('administer site configuration'),
     'file' => 'telegram_manager.pages.inc',
     'type' => MENU_LOCAL_TASK
   );
   $items['admin/config/telegram/manager/contact'] = array(
     'title' => 'Contacts',
     'description' => 'View contact list',
     'page callback' => 'telegram_manager_contact_list_page',
     'access arguments' => array('administer site configuration'),
     'file' => 'telegram_manager.pages.inc',
     'type' => MENU_LOCAL_TASK,
   );
   $items['admin/config/telegram/manager/contact/%telegram_manager_contact'] = array(
     'title' => 'Contact',
     'description' => 'View contact list',
     'page callback' => 'telegram_manager_contact_page',
     'page arguments' => array(5),
     'access arguments' => array('administer site configuration'),
     'file' => 'telegram_manager.pages.inc',
     'type' => MENU_CALLBACK,
   );
   $items['admin/config/telegram/manager/contact/%telegram_manager_contact/view'] = array(
     'title' => 'Contact',
     'type' => MENU_DEFAULT_LOCAL_TASK,
     'weight' => -10
   );
   $items['admin/config/telegram/manager/contact/%telegram_manager_contact/edit'] = array(
     'title' => 'Edit',
     'description' => 'View contact list',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('telegram_manager_contact_form',5),
     'access arguments' => array('administer site configuration'),
     'file' => 'telegram_manager.pages.inc',
     'type' => MENU_LOCAL_TASK,
   );
   return $items;
}

/**
 * Get Telegram manager.
 *
 * @return DrupalTelegramManager
 */
function telegram_manager() {
  $telegram = &drupal_static('telegram');
  if (!isset($telegram['manager'])) {
    $client = telegram_client();
    $telegram['manager'] = new DrupalTelegramManager($client, new DrupalTelegramStorage());
  }
  return $telegram['manager'];
}

/**
 * Menu loader for contact.
 *
 * @param int $oid
 *   Contact's object id.
 */
function telegram_manager_contact_load($oid) {
  $contacts = telegram_manager()->getContacts(array('oid' => $oid));
  return reset($contacts);
}

/**
 * Menu loader for message.
 *
 * @param int $oid
 *   Contact's object id.
 */
function telegram_manager_message_load($oid) {
  $contacts = telegram_manager()->getMessages(array('oid' => $oid));
  return reset($contacts);
}

/**
 * Implements hook_cron().
 */
function telegram_manager_cron() {
  // Read incoming messages and store.
  if (telegram_client()->start()) {
    telegram_manager()->readNewMessages(100);
  }
}

/**
 * Implements hook_cron_queue_info()
 */
function telegram_manager_cron_queue_info() {
  $queues['telegram_manager'] = array(
    'worker callback' => 'telegram_manager_queue_worker',
    // Max runtime per cron run.
    'time' => 30,
  );

  return $queues;
}

/**
 * Queue worker callback
 */
function telegram_manager_queue_worker($item) {
  $result = telegram_manager()->processJob($item);
}


