<?php
/**
 * @file
 * Drupal module: Telegram
 *
 * Experimental development, guess what...
 *
 * By Jose Manuel Guerrero & Jose Reyero
 *
 * http://reyero.net
 * http://jmanuelguerrero.com
 */

use Drupal\telegram\DrupalTelegramClient;

/**
 * Implements hook_menu().
 */
 function telegram_menu() {
   $items['telegram/test'] = array(
     'title' => t('Telegram Test'),
     'page callback' => 'drupal_get_form',
     'page arguments' => array('telegram_test_form'),
     'access arguments' => array('administer site configuration'),
     'file' => 'telegram.admin.inc',
   );
   $items['admin/config/telegram'] = array(
     'title' => t('Telegram Settings'),
     'page callback' => 'drupal_get_form',
     'page arguments' => array('variable_module_form', 'telegram'),
     'access arguments' => array('administer site configuration'),
   );
   return $items;
}

/**
 * Send message to phone number.
 */
function telegram_send_phone($phone, $text) {
  return telegram_client()->sendToPhone($phone, $text);
}

/**
 * Send message to user.
 */
function telegram_send_user($account, $text) {

}

/**
 * Get Telegram client
 */
function telegram_client() {
  static $client;

  if (!isset($slient)) {
    $client = new DrupalTelegramClient(
        variable_get_value('telegram_command_exec'),
        variable_get_value('telegram_command_key'),
        variable_get_value('telegram_command_debut')
    );
  }

  return $client;
}