<?php
/**
 * @file
 * Drupal module: Telegram
 *
 * Experimental development, guess what...
 *
 * By Jose Manuel Guerrero & Jose Reyero
 *
 * http://reyero.net
 * http://jmanuelguerrero.com
 */

use Drupal\telegram\DrupalTelegramClient;

/**
 * Implements hook_menu().
 */
function telegram_menu() {
   $items['admin/config/telegram'] = array(
     'title' => 'Telegram',
     'access arguments' => array('administer site configuration'),
     'position' => 'right',
     'page callback' => 'system_admin_menu_block_page',
     'access arguments' => array('access administration pages'),
     'file' => 'system.admin.inc',
     'file path' => drupal_get_path('module', 'system'),
   );
   $items['admin/config/telegram/settings'] = array(
     'title' => 'Settings',
     'description' => 'Configure Telegram',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('variable_module_form', 'telegram'),
     'access arguments' => array('administer site configuration'),
   );
   $items['admin/config/telegram/test'] = array(
     'title' => 'Test',
     'description' => 'Test configuration settings',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('telegram_test_form'),
     'access arguments' => array('administer site configuration'),
     'file' => 'telegram.admin.inc',
   );
   $items['admin/config/telegram/send'] = array(
     'title' => 'Send',
     'description' => 'Try sending messages manually',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('telegram_send_form'),
     'access arguments' => array('administer site configuration'),
     'file' => 'telegram.admin.inc',
   );
   $items['admin/config/telegram/contacts'] = array(
     'title' => 'Contacts',
     'description' => 'Manage contact list',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('telegram_contact_list_form'),
     'access arguments' => array('administer site configuration'),
     'file' => 'telegram.admin.inc',
   );
   return $items;
}

/**
 * Send message to phone number.
 */
function telegram_send_phone($phone, $text) {
  return telegram_client()->sendToPhone($phone, $text);
}

/**
 * Send message to user.
 */
function telegram_send_user($account, $text) {

}

/**
 * Get Telegram client
 */
function telegram_client() {
  static $client;

  if (!isset($slient)) {
    $client = new DrupalTelegramClient(array(
      'command' => variable_get_value('telegram_command_exec'),
      'keyfile' => variable_get_value('telegram_command_key'),
      'homepath' => variable_get_value('telegram_command_cwd'),
      'configfile' => variable_get_value('telegram_config_path'),
      'debug' => variable_get_value('telegram_command_debug')
    ));
  }

  return $client;
}