<?php

/**
 * Drupal module: Telegram CLI
 */

use Drupal\telegram_cli\DrupalTelegramClient;
use Drupal\telegram_cli\TelegramProcess;

/**
 * Get Telegram client
 *
 * @return Drupal\telegram_cli\TelegramClient
 */
function telegram_cli_client() {
  $telegram = &drupal_static('telegram');
  if (!isset($telegram['client'])) {
    $telegram['client'] =  new DrupalTelegramClient(telegram_cli_process(), telegram_logger());
  }
  return $telegram['client'];
}

/**
 * Gets / creates a Telegram CLI Process
 *
 * @return \Drupal\telegram_cli\TelegramProcess
 */
function telegram_cli_process() {
  return new TelegramProcess(_telegram_cli_params(), telegram_logger());
}

/**
 * Get configuration as array.
 */
function _telegram_cli_params() {
  return array(
      'command' => variable_get_value('telegram_command_exec'),
      'keyfile' => variable_get_value('telegram_command_key'),
      'homepath' => variable_get_value('telegram_command_cwd'),
      'configfile' => variable_get_value('telegram_config_path'),
      'debug' => variable_get_value('telegram_command_debug'),
  );
}