<?php

/**
 * Drupal Module: Telegram Bot
 */

use Drupal\telegram_bot\TelegramBotInterface;
use Drupal\telegram_bot\TelegramBotManager;
use Drupal\telegram_bot\TelegramBotWebhookInterface;

/**
 * Implements hook_menu().
 */
function telegram_bot_menu() {
  $items['admin/config/telegram/bot'] = array(
    'title' => 'Telegram Bot',
    'description' => 'Configure Telegram',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('variable_group_form', 'telegram_bot_enabled'),
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/config/telegram/bot/enabled'] = array(
    'title' => 'Enabled Bots',
    'description' => 'Configure Telegram',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  if ($bot_manager = telegram_bot_manager()) {
    $webhook_enabled = array_filter(variable_get_value('telegram_bot_enabled_webhook'));
    foreach ($bot_manager->getDefinitions() as $bot_id => $info) {
      $items['admin/config/telegram/bot/' . $bot_id] = array(
        'title' => $info['label'],
        'type' => MENU_LOCAL_TASK,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('variable_group_form', 'telegram_bot_' . $bot_id),
        'access arguments' => array('administer site configuration'),
      );

      // Webhook for Telegram Bot if enabled.
      if (!empty($webhook_enabled[$id])) {
        $items['telegram/bot/' . $id . '/%'] = array(
            'title' => 'Telegram Bot Webhook',
            'page callback' => 'telegram_bot_webhook',
            'page arguments' => [$id, 1],
            'access arguments' => TRUE,
        );
      }
    }

  }


  return $items;
}

/**
 * Gets the Telegram Bot Manager service.
 *
 * @return \Drupal\telegram_bot\TelegramBotManager
 */
function telegram_bot_manager() {
  return telegram_service('telegram_bot.manager');
}

/**
 * Invoke cron on all bots.
 */
function telegram_bot_cron() {
  $enabled = array_filter(variable_get_value('telegram_bot_enabled_cron'));
  foreach (array_filter($enabled) as $id) {
    if ($bot = telegram_bot_manager()->getTelegramBot($id)) {
      $bot->invokeCron();
    }
  }
}

/**
 * Page callback: Bot Webhooks.
 */
function telegram_bot_webhook($bot_id, $bot_key = NULL) {
  $bot = telegram_bot_manager()->getTelegramBot($bot_id);
  if ($bot && $bot->validateKey($bot_key)) {
    return $bot->invokeWebhook();
  }
  else {
    drupal_access_denied();
  }
}

